# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temperature.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\x12\x0btemperature\"7\n\x12TemperatureRequest\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x12\x0c\n\x04unit\x18\x02 \x01(\t\"*\n\x13TemperatureResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x32\xb4\x04\n\x14TemperatureConverter\x12Z\n\x13\x43\x65lsiusToFahrenheit\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\"\x00\x12Z\n\x13\x46\x61hrenheitToCelsius\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\"\x00\x12V\n\x0f\x43\x65lsiusToKelvin\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\"\x00\x12V\n\x0fKelvinToCelsius\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\"\x00\x12Y\n\x12KelvinToFahrenheit\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\"\x00\x12Y\n\x12\x46\x61hrenheitToKelvin\x12\x1f.temperature.TemperatureRequest\x1a .temperature.TemperatureResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPERATUREREQUEST._serialized_start=34
  _TEMPERATUREREQUEST._serialized_end=89
  _TEMPERATURERESPONSE._serialized_start=91
  _TEMPERATURERESPONSE._serialized_end=133
  _TEMPERATURECONVERTER._serialized_start=136
  _TEMPERATURECONVERTER._serialized_end=700
# @@protoc_insertion_point(module_scope)
